### ISSUE TITLE
problem by running MNIST example

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/htm.core#838] opened 2020-06-13 11:15 UTC
Hi all,
have just downloaded and installed the current version.
After installing I run mnist_sp and have the following error:
```
~/nupic/current/htm.core/build/Release/bin$ ./mnist_sp 
------------CPP SpatialPooler Parameters ------------------
iterationNum                = 0
iterationLearnNum           = 0
numInputs                   = 784
numColumns                  = 6272
numActiveColumnsPerInhArea  = 0
potentialPct                = 0.1
globalInhibition            = 1
localAreaDensity            = 0.1
stimulusThreshold           = 6
synPermActiveInc            = 0.14
synPermInactiveDec          = 0.002
synPermConnected            = 0.5
minPctOverlapDutyCycles     = 0.2
dutyCyclePeriod             = 1402
boostStrength               = 2
spVerbosity                 = 1
wrapAround                  = 1
version                     = 2
CPP SP seed                 = 4
Error opening file
Error opening file
Error opening file
Error opening file
===========BASELINE: no SP====================
Training for 0 cycles ...
```
I think, it is a problem with the name of mnist files.
Does anyone have this problem?

**Comment by breznak** [comment] 2020-06-15 15:05
> Error opening file 

it is possible that the mnist dataset is not correctly shipped in the release. 

Thanks for reporting, though it's low on priority I'd say. You can workaround it by running the `cmake` configure stage of the build, it'll download and unpack the dataset for you.

**Comment by Zbysekz** [comment] 2020-06-26 13:34
Reporting the same as @Thanh-Binh

> by running the cmake configure stage of the build,

@breznak what exactly you mean by that?

Thanks

**Comment by breznak** [comment] 2020-06-29 07:46
> have just downloaded and installed the current version. 

I assume this means you're running the binary release downloaded from this page. I am suggesting to build from sources and see if that's fixed (?)

**Comment by Zbysekz** [comment] 2020-06-29 13:36
> > have just downloaded and installed the current version.
> 
> I assume this means you're running the binary release downloaded from this page. I am suggesting to build from sources and see if that's fixed (?)

I've build from source on Ubuntu...

**Comment by breznak** [comment] 2020-06-30 20:28
sorry, I have to have a look at this. 
We should then turn the MNIST into a minimal test so it gets run consistently in CI.

**Comment by Thanh-Binh** [comment] 2020-07-01 05:43
Thanks for your bug fixed. 
Currently, we do classify just after training without saving the trained HTM model into a file.
Last year I reported a bug by saving after training, and then loading it again for classification.
The classification results are not the same for both cases. I really do not know if it is fixed?
Do you know it?

**Comment by breznak** [comment] 2020-07-01 08:55
Ok, thank you for reporting. 
I could replicate the problem but the example works as intended in a "normal" scenario. 
The problem is in filepaths to the data files, it could be improved but I'll keep it as "low". PR always welcome. 

BROKEN: 
> After installing I run mnist_sp and have the following error:
~/nupic/current/htm.core/build/Release/bin$ ./mnist_sp 

```
cd Release/bin
./mnist_sp
```

WORKS:
```
cd Release
./bin/mnist_sp

//or
cd build/scripts
../Release/bin/mnist_sp
```

I'll add a demo to our CI so this is run continuously and people can see how to run the files. 


> Last year I reported a bug by saving after training, and then loading it again for classification.
The classification results are not the same for both cases. I really do not know if it is fixed? 

Recently we've reworked serialization of Connections (SP,TM) quite a bit, and several bugs were fixed by that. Please retry now your serialization experiment and let us know :+1: I think it most likely should be fixed. If you can make a PR with a unit test for that, it'll be great!

**Closed** 2020-07-01 22:43 UTC
Labels: bug, example, low
