### ISSUE TITLE
What is the parmeter externalPredictiveInputs for?

### ISSUE THREAD

**Issue by SebastianEd** [htm-community/htm.core#817] opened 2020-06-01 18:00 UTC
Hello.

Currently I'm struggling with the parameter externalPredictiveInputs. I do not fully understand how it works and what it's there for. I tried to link two different TMs using the parameter, but it did not result in changing any learning behaviour, even though it connected some synapses.
Maybe you can explain the reason of existence for the parameter and tell me how to work with it properly. 

Thank you in advance!

**Comment by breznak** [comment] 2020-06-01 18:36
Hi @SebastianEd , can you show an example of what does not work for you? 

> Currently I'm struggling with the parameter externalPredictiveInputs. I do not fully understand how it works and what it's there for.  

You're right, this lets the TM to learn (link synapses) with output from "another region" which is out of scope of this TM. Another TM or some other input are good candidates. 

```
 * @param externalPredictiveInputs
* Number of external predictive inputs.  These values are not related to this
* TM, they represent input from a different region.  This TM will form
* synapses with these inputs in addition to the cells which are part of this
* TemporalMemory.  If this is given (and greater than 0) then the active
* cells and winner cells of these external inputs must be given to methods
* TM.compute and TM.activateDendrites
```
>  I tried to link two different TMs using the parameter, 

yes, that sounds like a good usecase to me.  

> ...but it did not result in changing any learning behaviour, even though it connected some synapses.

It's hard to say what the problem is. It seems some new synapses are connected, so this would work(?). If that does not change anything, it might be an issue of data, params, etc.

**Comment by SebastianEd** [comment] 2020-06-01 19:16
At first I should probably say that I am working on a scientific paper for my university, which analyses the parameters of the htm.core implementation. So I'll be glad for ANY information and help :)

So for my test, I try to keep the parameters and values as low as possible to more easily understand 
what's happening. I chose a SDR with the size of 64 bits. 

I've got two arrays with different data. These are my two sequences, the HTM should learn:
1. UInt sensor_data[8] = { 2, 2, 2, 2, 3, 3, 3, 3 };
2. UInt sensor_data_two[8] = { 1, 2, 3, 2, 5, 6, 7, 8 };

For encoding these values I'm using the ScalarEncoder with following parameters:

```
ScalarEncoderParameters encoder_params;
encoder_params.activeBits = 8;			
encoder_params.minimum = 1;				
encoder_params.maximum = 8;				
encoder_params.category = true;	
```		

Next the parameters of my TMs. The only difference to my first TM is, that the externalPredictiveInputs parameter is 0, because I do not give him any external inputs.
```
TemporalMemory tm(
64,	        // columnDimensions
2,		// cellsPerColumn
2,		// activationThreshold
0.21,		// initialPermanence
0.50,		// connectedPermanence
1,		// minThreshold
10,		// maxNewSynapseCount	
0.10,	        // permanenceIncrement
0.10,	        // permanenceDecrement
0.0,		// predictedSegmentDecrement
42,		// seed
2,		// maxSegmentsPerCell
20,		// maxSynapsesPerSegment
true,		// checkInputs
64,		// externalPredictiveInputs
TemporalMemory::ANMode::RAW
);
```
So for the test itself I am doing the following for every iteration. 
First I am adding 20% noise to the SDR, which the first TM is given to. I do this because I expect to see an anomaly score higher than 0.0 in the second TMs result (I am not sure if this should be the case).  After that I am passing the active and the winner cells to the second TM.

```
//  This is executed in a for-loop

encoded_sdr.addNoise(0.2);

tm.compute(encoded_sdr, true);

// Get the active and winner cells and parse them into a dense SDR with the size of 64 bits
auto externalPredictiveInputsActive = getDenseSdr(64, tm.getActiveCells());
auto externalPredictiveInputsWinner = getDenseSdr(64, tm.getWinnerCells());

secondTm.compute(encoded_sdr_two, true, externalPredictiveInputsActive, externalPredictiveInputsWinner);	

```

This is the output of my last iteration. As you can see, the first TM has a raw anomaly score of 37.5% which can be expected with the given parameters and noise. The second TM predicts its next input (which you cannot see on the picture) perfectly fine. And that is exactly my problem. I expected the second TM to form synapses with some of the active cells of the first TM, which I believed, should result in an anomaly score higher than 0.0. 

![grafik](https://user-images.githubusercontent.com/27292056/83444177-48da7400-a44b-11ea-8da2-75659292c7d7.png)

I am quite sure that I'm doing something wrong and for that reason I want to understand how to work with the externalPredictiveInputs parameter. Also if you have any good examples or use cases in mind, which clearly shows the effect of the parameter, I'd be glad to try them out.

**Comment by breznak** [comment] 2020-06-01 19:39
> At first I should probably say that I am working on a scientific paper for my university, which analyses the parameters of the htm.core implementation. 

glad to hear! :+1: Be sure to read/check our tries with NAB wrt params: #205 

> I've got two arrays with different data. These are my two sequences, the HTM should learn:
    UInt sensor_data[8] = { 2, 2, 2, 2, 3, 3, 3, 3 };
    UInt sensor_data_two[8] = { 1, 2, 3, 2, 5, 6, 7, 8 };

just checking, are you sure what you're doing and you specificaly want to use `externalPredictiveInputs` ? 
As a) that area is not that well researched/implemented, b) for "evaluating impact of params on HTM" that param is not needed, c) HTM must learn the 2 sequences in a single (H)TM. 

>  I chose a SDR with the size of 64 bits. 

I'd say too short, and HTM might not learn,work well. Stick to the "standard" size 2048+ for SP,TM. And relatively appropriate input. (ofc you might tune the example well to work, but if you use defaults, keep the sizes up). 

> The second TM predicts its next input (which you cannot see on the picture) perfectly fine. And that is exactly my problem. I expected the second TM to form synapses with some of the active cells of the first TM, which I believed, should result in an anomaly score higher than 0.0. 

- again, too small TMs,SPs..hard to say if/why things work at all then. 
- I haven't looked exactly, but my insight is that TM2 learns with "the good cells" from TM1 (ie those anomalous from your noice are not included), hence you get perfect score on tm2.

**Comment by SebastianEd** [comment] 2020-06-01 21:15
> glad to hear! 👍 Be sure to read/check our tries with NAB wrt params: #205 

I've already had a look at NAB and the Anomaly Liklehood, but am not finished, yet. :)

> just checking, are you sure what you're doing and you specificaly want to use externalPredictiveInputs ?
> As a) that area is not that well researched/implemented, b) for "evaluating impact of params on HTM" that param is not needed, 

I've already evaluated the impact of the remaining parameters (except the anomaly mode. But I'm also working on that). So for completeness of my research I'd like to describe the externalPredictiveInputs, as well. 

> c) HTM must learn the 2 sequences in a single (H)TM.

I did not know that the 2 sequences must be learned in one single TM. Maybe you can explain that further and also explain why the parameter externalPredictiveInputs was implemented/needed in the first place.

> I'd say too short, and HTM might not learn,work well. Stick to the "standard" size 2048+ for SP,TM. And relatively appropriate input.

I also tried it with the standard size of 2048 bits. But I could not see any changes with that. I also think that the size does not matter that much, as long as you adjust your other parameters to that. Also 64 bits were enough to clearly show the impact of most of the other parameters and learn those small sequences I'm using for testing. 

> I haven't looked exactly, but my insight is that TM2 learns with "the good cells" from TM1 (ie those anomalous from your noice are not included), hence you get perfect score on tm2.

I am sorry to not make this clear. That was clearly my fault. 👍 
The first TM gets the first encoded sequence ( which is { 2, 2, 2, 2, 3, 3, 3, 3 }) and also to that sequence the noise is added. This results in an anomaly score of 37.5%, as you can see in the first half of the screenshot. Next this result is given to the second TM as external inputs. I believe that synapses are grown over the two TMs but I cannot see any impact on the learning behaviour. It does not speed up the learning, nor has it any impacts on the predictions, as you can see in the second half of the screenshot.

Because there are hardly any information about the parameter, I don't have any clues what this parameter should do and therefore cannot make any good assumptions. That makes it hard to do researches on it. A well defined use case would help with that. Also if anyone uses the parameter externalPredictiveInputs, it would be nice to share their experiences.

**Comment by breznak** [comment] 2020-06-01 21:57
> I've already evaluated the impact of the remaining parameters 

It'd be great if you could share the results, or atleast methodology with us, as the params are, unfortunately, interweaved, so it's rather difficult to evaluate impact (practical/theoretical) of each (or pairs). 

> I did not know that the 2 sequences must be learned in one single TM.

no, it means a single TM must (be able to) learn 2 sequences (obviously). Do put a single sequence in each TM if you know what you're doing. 

> Maybe you can explain that further and also explain why the parameter externalPredictiveInputs was implemented/needed in the first place.

it is to include external sensory data/TM to your running TM. The docs are not very good at that one, nor there is a real-world example. 

> Next this result is given to the second TM as external inputs. I believe that synapses are grown over the two TMs 

there are no synapses literally grown between the 2 TMs, it's just your 2nd TM gets the "hints" from external inputs, so IT grows synapses also to those cells. (well, yeah, so the "growing" is questionable). 

> but I cannot see any impact on the learning behaviour. It does not speed up the learning, nor has it any impacts on the predictions, 

because your 2nd sequence is useless for the 1st TM. 

> A well defined use case would help with that 

my high-level example: 

TM1: `apple->eat, poison->die, banana->eat, mushroom->eat, mushroom->die.`
TM1(mushrooom)=? (eat/die?)
TM2: `apple->red, ...., mushroom->brown, mushroom->red`
with external inputs: 
TM1(mushroom|brown)=eat && TM1(mushroom|red)=die.

**Comment by SebastianEd** [comment] 2020-06-03 13:04
Thank you very much. Your high-level exmaple helped me a lot to validate my understanding about the parameter. For this I made the following test (I don't use the SP, because I only want to analyse the TM):

I've got two TMs, labeld as TM-1 and TM-2, with the following parameters:

```
TemporalMemory tm(
10,	        // columnDimensions
2,		// cellsPerColumn
2,		// activationThreshold
0.21,		// initialPermanence
0.50,		// connectedPermanence
2,		// minThreshold
4,		// maxNewSynapseCount	
0.10,	        // permanenceIncrement
0.10,	        // permanenceDecrement
0.0,		// predictedSegmentDecrement
42,		// seed
2,		// maxSegmentsPerCell
20,		// maxSynapsesPerSegment
true,		// checkInputs
10,		// externalPredictiveInputs
TemporalMemory::ANMode::RAW
);
```
The only difference between TM-1 and TM-2 is, that TM-1s externalPredictiveInputs is 0, because it does not get any external inputs.

The TM-1 learns following sequence: 
* apple->red; poison->pink; banana->yellow; mushroom->brown; mushroom->red;

while the TM-2 learns this sequence:
* apple->eat; posion->die; banana->eat; mushroom->eat; mushroom->die;

The test is divided in three different learning phases. In phase 1, the TM-1 learnt its sequence for 50 epochs, while TM-2 does nothing. Then in phase 2, the TM-1 still is computing its sequence, but the TM-2 also starts learning its sequence, while getting the external inputs from TM-1. In phase 3, after another 50 epochs of learning, the sequence of TM-2 is slightly changed by switching "mushroom->eat" and "mushroom->die". So we've got:
* apple->eat; posion->die; banana->eat; mushroom->die; mushroom->eat;

The data are encoded by simply encoding a string with three characters into a SDR with 10 bits. E.g. "ra-" means that this is a red apple, while "-be" means, that there is "banana->eat". I hope you get the idea, that I'm always using the first letter of the words (the "-" is just a placeholder).
The first 4 bits of the encoded SDR represent the color, the next 4 bits represent the object and the last 2 bits represent the actions (eat or die). With the given sequences we always get an encoded SDR with 10 bits, of which two are active. 

I'll list the whole encoding, so you know what each bit represents and can understand it more easily:

```
apple->red:        1000 1000 00
posion->pink:      0100 0100 00
banana->yellow:    0010 0010 00
mushroom->brown:   0001 0001 00
mushroom->red:     1000 0001 00

apple->eat:        0000 1000 10
posion->die:       0000 0100 01
banana->eat:       0000 0010 10
mushroom->eat:     0000 0001 10
mushroom->die:     0000 0001 01
```

---

Let's have a look on the results. The first screenshot shows the 249th iteration step in the second learning phase. As you can see, the TM-2 predicts two cells (in this case he predicts: "mushroom->die") which is correct. Also the segments of the TM-2 have 3.3 synapses connected on average, even though only 2 cells are active at a time.

![externalPredictiveInputs-test-a1](https://user-images.githubusercontent.com/27292056/83637206-805e3300-a5a7-11ea-8684-6a90bde5175c.PNG)

In phase 3 we switched the two inputs from the TM-2 as described above. You may realize, that the TM-2 now predicts 3 cells. That is because it learns "mushroom->die" while still getting the external input "mushroom->brown" from TM-1. But TM-2 did not forget what it learned before and cannot decide if a red or brown mushroom leads to death, now. 

![externalPredictiveInputs-test-a2](https://user-images.githubusercontent.com/27292056/83637633-3590eb00-a5a8-11ea-8e94-1c8a974e25ef.PNG)

For the next screenshot I unlinked the two TMs and repeated the three learning phases. In this picture you can see the 249th iteration step of the 3rd learning phase. As you can see, the TM-2 only predicts two cells and its segments have only two connected synapses. This is because he did not receive external inputs from the TM-1 and don't know anything about colors. Therefore he cannot refer to them. 

![externalPredictiveInputs-test-b2](https://user-images.githubusercontent.com/27292056/83637936-a801cb00-a5a8-11ea-89ab-efa8752b2ee1.PNG)

---

I hope anything is clear enough and this example helps to get an idea of what the parameter externalPredictiveInputs does. Thank you @breznak for your help! Also feel free to correct me, if I'm wrong with anything. 


Sebastian Ederer

**Comment by breznak** [comment] 2020-08-05 11:58
Closing as abandoned issue, please reopen if a followup is needed.

**Closed by breznak** 2020-08-05 11:58 UTC
Labels: TM, question
