### ISSUE TITLE
C++ Region and parameters in Specs?

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/htm.core#643] opened 2019-08-20 12:57 UTC
@dkeeney: In Region (implemented by users), all user-defined parameters of a region are defined and assigned by a default value in the Specs. Users can change a parameter in run-time by using something like
params.getScalarT<parameter_data_type>("parameter_name")
in the constructor, e.g.
MyRegion(const ValueMap& params, Region *region) : RegionImpl(region)

But there is a small difference between using them by nupic.core and htm.core:
**By nupic.core:**
user can change some important parameters of them by calling
params.getScalarT<parameter_data_type>("parameter_name")
and other parameters are set by default value in the Specs.

**By htm.core:**
User have to call all of them.
If you do it in the way like nupic.core, other parameters are NOT set correctly by default value.
I really do not know if it is a bug or a new feature.
If it is a new feature, I hate it, especially when the number of region parameters are high, and only some of them are changed more often, other are rare ..
--> I'd like to recommend to fix it.

What do you think?
Thanks, Binh

**Comment by dkeeney** [comment] 2019-08-20 15:18
This should work exactly like nupic.core.

There are two types of objects here.
- Region  which is a generic object that represents the region
- RegionImpl subclasses which are implementations of the region.  I will refer to this as the "plugin" because these can be written in either C++ or python even if the app is not the same language.  The plugins can be user written or they may be the buillt-in C++ written implementations.  They can be mixed within a single app.

The user app should not directly call the region implementations or plugins.  Instead they call the generic functions on the Region class.

Parameters can be set by the user app in two ways:
- During region creation: When creating the region using `network.addRegion(name, type, parameters)`.  The third argument is an JSON or YAML string describing the arguments that are different than the default.
- After region creation: An application can call one of the region.setParameterXXX(name, value ) functions for anything it wants to change.  When called the Region object will pass this value on to the Region implementation or plugin by calling its corresponding function.   It does this ONLY if the parameter spec has ReadWrite permissions.  Normally the plugin will use this to change the corresponding parameter that it extracted during constructor.

Let me expand on what happens during region creation.   Ehe JSON or YAML parameter string given in the addRegion( ) function is parsed and merged with the default parameter values from the Spec.  So if a parameter is not mentioned in the parameter string its value will be obtained from the default value in the Spec.  This combined set of parameters is the ValueMap that is passed to the plugin as the first argument of the constructor.  The plugin constructor can use the values in this ValueMap to create the algorithm object which it is implementing or it can extract the parameters and put them in local variables for use later.    The ValueMap gets deleted when the constructor exits.

The params.getScalarT<parameter_data_type>("parameter_name") is the way the plugin extracts the parameter values out of the ValueMap.  All parameters listed in the Spec should have a value.  It will be the value passed in the parameter string or it will be the default value from the Spec.

Sometimes it is not until the  initalization( ) function call that the plugin has enough information to create its algorithm's class.  If so, it must extract and set aside all of the parameters it wants to use before returning from its constructor.  After a plugin has been instantiated, any of the setParamterXXX( name, value) calls should replace the value that the plugin set aside, or if the algorithm's class has already been created, pass the changed value on into the algorithm if the algorithm allows (has ReadWriteAccess permissions in the spec).

I hope this explanation is useful.

**Comment by Thanh-Binh** [comment] 2019-08-20 16:47
@dkeeney: 
Yes, I use the plugin constructor as you mentioned, but the behavior is not the same. Maybe it is a bug here?
I prefer to use default value for some parameters, than use setParameter()

**Comment by dkeeney** [comment] 2019-08-20 17:21
> I prefer to use default value for some parameters, than use setParameter()

If you passed a " " in the third argument to the `addRegion(name, type, "") `  Then `params.getScalarT<parameter_data_type>("parameter_name") ` **will return the default value from Spec.**

You do not have to use the params.getScalarT function at all, you can assign your own defaults in the body of your plugin if you choose.  It is up to you if you wish to use the values that were prepared for you in the ValueMap.  

This is exactly how Nupic operated.

**Comment by Thanh-Binh** [comment] 2019-08-21 18:04
@dkeeney thanks for your information.
In my test, I have 2 parameters in Specs: "parameter1" with UInt32 and "parameter2" with data type Real32 and the default value 1.5. Both parameters are ReadWriteAccess.
I want to use the default value of "parameter2", and pass only "parameters1" via 
```addRegion(name, type, "{parameter1: 100}")```
and get it by using
```
params.getScalarT<UInt32>("parameter1")
std::cout << parameter2 << std::endl;
```
In consol, I see parameter2 has the value 0, It is false!
You can easily test it and should have the feeling, it is a bug.

**Comment by dkeeney** [comment] 2019-08-21 18:58
Hmmm, that does sound like a bug.
Let me see if I can reproduce this.

**Comment by dkeeney** [comment] 2019-08-21 20:02
Ok I setup a test to confirm that it is working as it should.

In the constructor of the region TestNode.cpp are the following lines:
```
TestNode::TestNode(const ValueMap &params, Region *region)
    : RegionImpl(region), computeCallback_(nullptr), nodeCount_(1)
{
  // params for get/setParameter testing
    // Populate the parameters with values.
  outputElementCount_ = params.getScalarT<UInt32>("count");
  int32Param_ = params.getScalarT<Int32>("int32Param");
  uint32Param_ = params.getScalarT<UInt32>("uint32Param");
  int64Param_ = params.getScalarT<Int64>("int64Param");
  uint64Param_ = params.getScalarT<UInt64>("uint64Param");
  real32Param_ = params.getScalarT<Real32>("real32Param");
  real64Param_ = params.getScalarT<Real64>("real64Param");
  boolParam_ = params.getScalarT<bool>("boolParam");
... plus more
```

In the Spec of TestNode.cpp are:
```
  ns->parameters.add("uint32Param",
                     ParameterSpec("UInt32 scalar parameter", // description
                                   NTA_BasicType_UInt32,
                                   1,    // elementCount
                                   "",   // constraints
                                   "33", // defaultValue
                                   ParameterSpec::ReadWriteAccess));

  ns->parameters.add("real32Param",
                     ParameterSpec("Real32 scalar parameter", // description
                                   NTA_BasicType_Real32,
                                   1,      // elementCount
                                   "",     // constraints
                                   "32.1", // defaultValue
                                   ParameterSpec::ReadWriteAccess));

```

My test looks like this:   (I appened this to the end of NetworkTest.cpp)
```
/*
 * Test initalization of parameters for a region.
 * For this test we will use paramters: uint32Param and real32Param
 * on the TestNode region.  
 * For uint32Param we will initalize it in the addRegion( ) call.
 * For real32Param we will use the default value (32.1f)  in the Spec.
 */
TEST(NetworkTest, Parameters) {

  Network net;
  std::shared_ptr<Region> r = net.addRegion("level1", "TestNode", "{uint32Param: 100}");

  UInt32 uint32Param = r->getParameterUInt32("uint32Param");
  EXPECT_EQ(uint32Param, 100);

  Real32 real32Param = r->getParameterReal32("real32Param");
  EXPECT_EQ(real32Param, 32.1f);

  r->setParameterReal32("real32Param", 100.22f);
  real32Param = r->getParameterReal32("real32Param");  
  EXPECT_EQ(real32Param, 100.22f);
}
```

The test passes.

**Comment by dkeeney** [comment] 2019-08-21 20:03
I am getting expected behavior.  So I must not be understanding your question properly.

**Comment by Thanh-Binh** [comment] 2019-08-21 20:33
@dkeeney
I am very interested in knowing the value of „parameter2“ by internal use (within class like my test). In this case , no getParameter() Need!
Other question: 
Do I have to declare the class member „parameter2“? like
Real32 parameter2;

**Comment by dkeeney** [comment] 2019-08-21 21:16
From within your App, (like the test program) the only way to find out the value of any parameter in your region is via  `getParameterReal32("parameter2")`
I am assuming that your Region code contains a getParameterReal32(name, index) function and it will match the name "parameter2" and return that value.

From within your Region code, yes you need a variable for your parameter so `Real32 parameter2;` is appropriate to declare it.  Then to populate it you could assign it a value any way you want.  It is just a C++ variable.

What the following statement does for you is  go into the Spec, gets the default value for that parameter, and returns it as the appropriate type.  But, if a parameter with this name was also passed in the parameters field of addRegion(name, type, parameters )  then it will return that value instead.
```
Real32 parameter2 = params.getScalarT<Real32>("parameter2");
```

If what you really want is just the default value from the Spec regardless of the values in the addRegion( ) call, then here is what you have to do:
- fetch the Spec object.
- find the parameters, then lookup your parameter by name.
- Then on your parameter locate the default value.  It is a YAML or JSON string.
- use the YAML parser to decode it and then extract its value as Real32.
- assign it to your parameter2

I think I would just forget the Spec and do the following:
```
Real32 parameter2 = 1.5f;
```

**Comment by Thanh-Binh** [comment] 2019-08-22 14:34
@dkeeney:
I understood you all. But I am 100% sure that for each parameter in Specs we have to call
```params.getScalarT<parameter_data_type>("parameter_name")```
in the constructor.
If we did do this without passing parameters over addRegion(), the default value of all parameters will be 0, INDEPENDENT on what you set in Specs.
For testing it with your TestNode, you can put std::cout before and after calling like
```
TestNode::TestNode(const ValueMap &params, Region *region)
    : RegionImpl(region), computeCallback_(nullptr), nodeCount_(1)
{
  std::cout << "before: " << real64Param_ << std::endl;
  real64Param_ = params.getScalarT<Real64>("real64Param");
  std::cout << "after call getScalarT: " << real64Param_ << std::endl;
}
```
I think it is very clear to understand this bug.
Thanks.

**Comment by dkeeney** [comment] 2019-08-22 17:35
> If we did do this without passing parameters over addRegion(), the default value of all parameters will be 0, INDEPENDENT on what you set in Specs.

No, I just proved that if you DID call `params.getScalarT<parameter_data_type>("parameter_name")` it WOULD have the default value from the Spec.

If you do `std::cout << "before: " << real64Param_ << std::endl;` before the assignment to real64Param_ it would output garbage because nothing has been assigned to the variable.  Some compilers would even give you a warning.

Now, if you are getting 0, Independent of the default value in the spec then perhaps the spec is not setup correctly.  Are you sue you have the right number of arguments.  Each field should look something like this:
```
  ns->parameters.add("real64Param",
                     ParameterSpec("Real64 scalar parameter", // description
                                   NTA_BasicType_Real64,   // type
                                   1,      // elementCount
                                   "",     // constraints
                                   "64.1", // defaultValue
                                   ParameterSpec::ReadWriteAccess));
```

**Comment by breznak** [comment] 2019-09-18 06:05
Is this issue still relevant? it seems @dkeeney was not able to replicate the issue. So far it looks the problem is in (an incorrect?) user's setup. 

So we either need a better explanation, reproducible of the problem; or this can be closed.

**Comment by breznak** [comment] 2019-09-19 18:04
Closing, please reopen if you still have this problem.

**Closed by breznak** 2019-09-19 18:04 UTC
