### ISSUE TITLE
different MNIST scores after save and load SpatialPooler

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/htm.core#193] opened 2019-01-03 16:00 UTC
@ctrl-z-9000-times : I have just tested your example about mnist classification, and have an interesting effect. Using your original codes, I reached the same scores as in your report (i.e. 94%).
If I save data of SpatialPooler and SDRClassifier after training and load them again for inference mode (it is a common use way), the reached score is ONLY 84%.
I think maybe some other important parameters are not saved, so that they cause a performance problem.
Can you check again if this problem is understandable?
Best thanks.

**Comment by ctrl-z-9000-times** [comment] 2019-01-03 16:14
Thank you for pointing this out!  I will look into this later today after i get home from work.

**Comment by ctrl-z-9000-times** [comment] 2019-01-04 14:32
I reproduced the problem, but I don't know why it happens or how to fix it.  The mnist branch is a work in progress...

**Comment by Thanh-Binh** [comment] 2019-01-04 14:49
@ctrl-z-9000-times : by my current setting I modified your parameters as follows:
1. Input of SP should have the same image size, i.e. 28 x 28
2. columnDimension = {14, 14, 200}
so that we can reach the MNIST score of 96% @ very high frame rate.
The higher depth of SP, the better performance ...
SP is too slow by images at higher resolution like VGA.

Can SP process each active bit of input (in the case of image: brighter pixels) parallelly?

**Comment by Thanh-Binh** [comment] 2019-01-04 15:13
@ctrl-z-9000-times : The save problem is not only by your mnist branch, but also by the master nupic.cpp.

**Comment by ctrl-z-9000-times** [comment] 2019-01-04 15:35
> MNIST score of 96% @ very high frame rate.

I just now pushed a change which yields 95% score with SP size (10 x 10 x 120).   On my computer it runs in under 2 minutes.  The primary difference in this commit is to revert my method SP::initMapPotential_ back to the original version.

> Can SP process each active bit of input (in the case of image: brighter pixels) parallelly?

No, this SP can't.  In theory the SP could be made parallel but I don't think it's practical.  It would be easier to make two SP's in two threads than to have one SP with two threads.

> The save problem is not only by your mnist branch, but also by the master nupic.cpp.

Oh, that changes things...  I was looking only through this branches diffs.  I wonder why the SP unit tests didn't find this?

**Comment by Thanh-Binh** [comment] 2019-01-04 16:02
Do you use SDR input({28, 28, 1})?
I use it for speed up by the same score.

**Comment by Thanh-Binh** [comment] 2019-01-04 16:04
I am going to test with higher depth of SP ....

**Comment by Thanh-Binh** [comment] 2019-01-04 16:32
by increasing the SP-depth from 200 to 300, the score is slightly changed from 96% to 96.24%.
But the frame rate is reduced from 30Hz to 10Hz...
If I have time I will test them systematically....

**Comment by ctrl-z-9000-times** [comment] 2019-01-04 17:06
> Do you use SDR input({28, 28, 1})?
I use it for speed up by the same score.

Interesting. I use (28 x 28 x 2) like it is in the branch currently. I will have to try your dimensions.  Did you also modify the encoding too?

FYI for mnist dataset the human accuracy is around 98%.  So 96% is pretty darn good, especially considering the difference in complexity between this and the real human visual system.  

Have you tried using theflag `-t` which increases the training time?

**Comment by Thanh-Binh** [comment] 2019-01-04 18:14
I modified slightly your codes mainly 
1. for visualizing using opencv. 
2. read Mnist files, especially for converting dara_raw into vector<UInt> So that the length of this vector is the same as image size
3. change SDR and SP Parameters, 
If you want I can share you my code!

**Comment by ctrl-z-9000-times** [comment] 2019-01-04 18:21
> change SDR and SP Parameters,
If you want I can share you my code!

I think i can reproduce the code changes from your description.  Any parameter changes which improve score / speed they would be great to have.  Thanks!

**Comment by Thanh-Binh** [comment] 2019-01-04 18:54
Choose the right parameter set for SP is very interesting. Do you have any idea for using some optimization methods like Genetic Algorithm for this task?

**Comment by ctrl-z-9000-times** [comment] 2019-01-04 21:45
> @Thanh-Binh 
> Do you have any idea for [parameter] optimization methods?

Why yes I do.  In past experiments I've tried: genetics, particle-swarms, and statistics.  The statistics method I think is the most useful, so I will explain it in detail: Run a set of parameters several times, record each runs final score.  Change a single parameter and re-run  several more times.  Then do some math & statistics to determine if the new set of parameters is better, and find the p-value which is a measure of confidence in that result.  This information can say things like "I'm 95% confident that this change will yield a 10% improvement in accuracy".  

Then make a framework to do all of this for you.  Make a bunch of parameter changes, queue them all up, wait for the framework to run each one 3 times, and finally sort the results to see which ones worked best.  To make this easier, write a program to suggest a bunch of  parameter changes.  Also to make it easier to work with, the framework should manage the mountains of diagnostic data which this sort of program can create.  

I think that this method is easier to work with than other parameter optimization methods because it doesn't try a lot of different parameters, instead it gives a detailed analysis of a select few parameters.  I have an example implementation at:  https://github.com/ctrl-z-9000-times/sdr_algorithms/blob/master/ae.py

**Comment by Thanh-Binh** [comment] 2019-01-04 22:05
@ctrl-z-9000-times thanks for sharing very cool framework for optimizing parameters. I think statistics are traditional and very intuitiv methods, but GA will be more powerful.
How can I use your tool directly for SP-based mnist classification?

**Comment by ctrl-z-9000-times** [comment] 2019-01-04 22:20
> How can I use your tool directly for SP-based mnist classification?

You'd need to write a python3 function to call the experiment (which is C++) and to report the score back to the framework.  There is some documentation in the linked file, and I can answer some questions too.

**Comment by Thanh-Binh** [comment] 2019-01-05 08:48
@ctrl-z-9000-times: Before looking at your tool in detailed it is nice to ask for any difference between your idea and Numenta swarming solution? Can you point it out?

**Comment by Thanh-Binh** [comment] 2019-01-05 17:11
@ctrl-z-9000-times I never use any tool for tuning NUPIC parameters, and want to learn a liitle.
It is very kind of you to tell me in detailed how you ran a parameter optimization tool to get the current MNIST parameters´. thanks.

**Comment by Thanh-Binh** [comment] 2019-01-06 15:38
@ctrl-z-9000-times today I have an interesting bug by SP size (28 x 28 x 25), where SDR size of the SP-output is zero for all images. I am not able to fix this bug now, but from my feeling, it may be a problem with odd value of size?
Do you know it?

**Comment by ctrl-z-9000-times** [comment] 2019-01-07 01:00
> bug by SP size (28 x 28 x 25)

So the way the local inhibition works is: the final column dimension is the number of mini-columns in an SP, and the preceding dimensions describe an array of SP's.  Its a lot of little SP's, each with global inhibition over their little area of the image.  And the program makes a grid of them so that you get an approximate topology.

Your example is a (28 x 28) grid of spatial poolers with 25 mini-columns each, which is too few mini-columns.  Usually the parameters are checked for this condition, but I broke that check, Sorry!

With local area density = 0.015 the min # mini cols is 34 which scores 93%.

**Comment by Thanh-Binh** [comment] 2019-01-07 07:09
@ctrl-z-9000-times thank you very much for your explain...

**Comment by breznak** [comment] 2019-01-14 18:14
Waiting for MNIST to be yet merged to master. 
Is this still an issue?

**Comment by ctrl-z-9000-times** [comment] 2019-01-14 19:39
AFAIK this is still an issue

**Comment by breznak** [comment] 2019-02-09 10:16
This can be debuged with the native SP after #242  is working. I already had it in working state, but broke again with WIP autoinstall of MNIST data

**Comment by breznak** [comment] 2020-06-02 12:20
I have recently fixed some bugs in SP serialization, likely fixing this. Closing, please reopen if still valid.

**Closed by breznak** 2020-06-02 12:20 UTC
Labels: bug
