### ISSUE TITLE
htm.core installation issue in python 3.8.3 in windows10

### ISSUE THREAD

**Issue by anjanakiran** [htm-community/htm.core#863] opened 2020-07-10 11:58 UTC
I am unable to installing htm.core in my windows 10 .during installation i got below error help me
 ERROR: Could not find a version that satisfies the requirement htm.core (from versions: none)
ERROR: No matching distribution found for htm.core.

**Comment by Zbysekz** [comment] 2020-07-24 08:32
I recommend you to use Python 3.7, i also tried 3.8 but as far as i remember, the 3.8 is somewhat mixed with 3.7..
Next time also please write how are you installing htm.core, since there are several ways.

**Comment by dkeeney** [comment] 2020-07-24 13:28
@anjanakiran, the PyPi download installation only supports a limited number of OS platforms and only Python 3.7  (the one from python.org not Anaconda) because that is what we build for the regression tests.  As @Zbysekz  suggests you can use the standard Python 3.7 with the PyPi download or you may find more success by cloning or downloading the entire repository and building from sources.  Please refer to the procedures in README.md for building with sources on Windows.   I use standard Python 3.8.0 for development and debugging of the htm.core library but I will try Python 3.8.3 to make sure that works too. If you want to use Anacondra Python be sure to use the Anacondra cmd prompt.

**Comment by dkeeney** [comment] 2020-07-24 15:31
I installed the latest Python (version 3.8.5, 64bit) from python.org and it gives me a build error when building from sources. So, I will have to check this out.

**Comment by dkeeney** [comment] 2020-07-24 16:36
Apparently Python 3.8 needs a newer version of `importlib-metadata`.
See https://github.com/pytest-dev/pytest/issues/7371

So, I updated importlib-metadata from v0.23 to v1.7.0 and everything is working.
```
pip install importlib-metadata --upgrade
```
@anjanakiran please try this and see if this helps.

**Comment by anjanakiran** [comment] 2020-07-26 07:26
I tried both comand prompt and Anaconda prompt .I am geeting same error in both.
@dkeeney i will try this method also
pip install importlib-metadata --upgrade.
after that i will update you. thanku so much

**Comment by anjanakiran** [comment] 2020-07-29 06:12
@dkeeney i upgraded importlib-metadata. again im getting same issue

**Comment by dkeeney** [comment] 2020-07-29 13:30
It looks like for Python 3.8.x you will need to build htm.core from sources.
Follow the procedures in README.md.

**Comment by anjanakiran** [comment] 2020-08-05 07:07
i tried to install from build htm.core source i'm getting below error
![Screenshot (44)](https://user-images.githubusercontent.com/62331046/89382438-76c48900-d718-11ea-85e4-6be63091149a.png)

**Comment by dkeeney** [comment] 2020-08-05 12:20
Can you check to make sure you have CMake installed?
Maybe that is the file it cannot find.

**Comment by anjanakiran** [comment] 2020-08-05 13:02
yes CMake was installed

**Comment by dkeeney** [comment] 2020-08-05 14:57
@breznak  do you have any ideas of what to check?

**Comment by breznak** [comment] 2020-08-05 15:22
I have been quitely following the issue but don't really see any obvious flaw. 
What comes to my mind: 
- @anjanakiran your Windows username is "two words" (with a space), that could potentially be a problem for some internal python processing. Can you try either renaming the user (your home dir) to a single word name? 
- as suggested, do you see the same issue with py 3.7?

**Comment by N3rv0us** [comment] 2020-09-03 09:58
Seems like cmake is not found correctly.

Can you please run `where cmake` in a command prompt? The output should show the exact path of the cmake binary. 
(In my case it is `C:\Program Files\CMake\bin\cmake.exe`)

However, you could then try to copy the full path into the setup.py line [332](https://github.com/htm-community/htm.core/blob/master/setup.py#L332) and [350](https://github.com/htm-community/htm.core/blob/master/setup.py#L350) like this:
```python
subprocess.check_call([r"C:\Program Files\CMake\bin\cmake.exe", "-G", "Visual Studio 16 2019", 
    "-A", "x64", BUILD_TYPE, PY_VER, REPO_DIR])
```
Please note the `r` in front of the string so python won't interpret `\` as an escape char.

**Comment by anjanakiran** [comment] 2020-09-07 05:03
while i am running where cmake in command prompt. iam getting below error
INFO: Could not find files for the given pattern(s).

**Comment by anjanakiran** [comment] 2020-09-07 06:18
I also tried in python 3.7.9 i am getting below error
![Screenshot (59)](https://user-images.githubusercontent.com/62331046/92354466-fa9ad800-f0ff-11ea-9b26-794f087e3338.png)

**Comment by breznak** [comment] 2020-09-07 06:32
ok, now it's 2 different issues :) 

> running where cmake in command prompt. iam getting below error 

it does seem you don't have `cmake`. Just to doublecheck, what does `cmake --version` say? 
If cmake is not installed , you can do `pip install cmake`, or install in the standard way on your OS. 

> n python 3.7.9 i am getting below error
Screenshot (59) 

it does not find common packages (like pytest) on pip! Are you running some unstandard version of windows? (like 32bit), I assume no. Can you try manually installing dependencies by `pip install -r requirements.txt`, executed from the repo root. It must pass so the install can proceed.

**Comment by fenfeibani** [comment] 2020-10-24 16:17
@N3rv0us  where is the setup.py ?
    However, you could then try to copy the full path into the setup.py line 332 and 350 like this:
subprocess.check_call([r"C:\Program Files\CMake\bin\cmake.exe", "-G", "Visual Studio 16 2019", 
    "-A", "x64", BUILD_TYPE, PY_VER, REPO_DIR])

**Comment by dkeeney** [comment] 2020-10-24 16:39
The full path to CMake should be in your Path environment variable.
Like @breznak suggested, `cmake --version` needs to work so that any CMake driven build/install can find it.

**Comment by breznak** [comment] 2021-02-20 13:03
We now have python 3.8 as main baseline, tested in all CI. So it should work fine. 
Closing, as always, reopen if you still need help

**Closed by breznak** 2021-02-20 13:03 UTC
Labels: build, platform

**Comment by HMaker** [comment] 2021-06-23 01:10
> We now have python 3.8 as main baseline, tested in all CI. So it should work fine.
> Closing, as always, reopen if you still need help

Tried this with Python 3.8.9
```
❯ pip install -i https://test.pypi.org/simple/ htm.core
Looking in indexes: https://test.pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement htm.core
ERROR: No matching distribution found for htm.core
```
```
❯ python -V && pip -V
Python 3.8.9
pip 20.3.3 from /home/hmaker/projects/htm/.venv/lib/python3.8/site-packages/pip (python 3.8)
```
