### ISSUE TITLE
Fail to build HTM.core (HEAD)

### ISSUE THREAD

**Issue by marty1885** [htm-community/htm.core#890] opened 2020-09-18 15:43 UTC
I'm trying to build htm.core using pip today and ran into some errors. After some digging, I believe this is the same error reported [on the forum](https://discourse.numenta.org/t/cant-install-htm-core/7877). (I can't locate where pip generates the makefile so I generated one from CMake directly). It shows the following error:

```
/home/marty/Documents/not-my-projects/htm.core/build/ThirdParty/cereal/cereal-src/include/cereal/external/rapidjson/reader.h:1012:53: error: comparison is always true due to limited range of data type [-Werror=type-limits]
 1012 |                 if ((sizeof(Ch) == 1 || unsigned(e) < 256) && CEREAL_RAPIDJSON_LIKELY(escape[static_cast<unsigned char>(e)])) {
      |                                         ~~~~~~~~~~~~^~~~~
```

The issue seems simple and I wanted to post a fix. But I can't figure out what's going on with cereal;Etaler also uses cereal but it isn't showing the same error. Maybe it is limited to the specific cereal version HTM.core is using?

Compiler: GCC 10.2.0
OS: Arch Linux

Best regards,
Martin

**Comment by dkeeney** [comment] 2020-09-18 16:58
I assume you are using the current version of Python which is 3.8.x
Currently we are building for Python 3.7 for the pip install.  So it will not find a match. Eventually we will get that updated to Python 3.8 but in the mean time you can build from sources.

To confirm that this is all still working, I created a new virtual machine and installed Ubuntu 20.04.  Here are the things I needed to install before I could get this to work.
```
sudo apt update
sudo apt -y upgrade
sudo apt install build-essential
sudo apt install git
python3 -V                #To confirm that python3 is already installed
sudo apt install python3-pip
cd to-where-clone-will-be-placed.
sudo git clone https://github.com/htm-community/htm.core.git
cd htm.core
sudo pip3 install -r requirements.txt
python3 setup.py install --user --force
python3 setup.py test
```
Of course your environment may be different and you will need to make some adjustments.

I will also try setting up another virtual machine with Mint since that was the original problem.

**Comment by marty1885** [comment] 2020-09-19 02:00
Yes, I'm using Python 3.8. I should have specified my environment more clearly. 

I don't think the bug is related to Python 3.8 tho. The error is still there even if I ran CMake directly.

```
git clone https://github.com/htm-community/htm.core.git --recursive
cd htm.core
mkdir build
cd build
cmake ..
make -j
```

**Comment by dkeeney** [comment] 2020-09-19 12:35
Oh, building that way might be a problem...
CMake needs to be ran from build/scripts.  Otherwise the ThirdParty components are in the wrong place and the wrong things get into the CMake cache.
To correct this, you need to delete the build folder completely and start over.
```
  cd htm.core
  rm -r build
  mkdir -p build/scripts
  cd build/scripts
  cmake ../..
  make -j4 install
```
Remember that building this way only builds the C++ components.  If you also need the Python bindings then rather than running CMake directly you need to build using setup.py so that it knows which python it is building for.
```
  python setup.py install --user --force
```
of course, --user and --force are not be needed if you setup a python environment.

Now, that does not address the "[-Werror=type-limits]" error you are seeing.
I was not able to reproduce this error when building on Ubuntu 20.
We are using Cereal 1.3.0 which is the latest and it has not changed for a while.

**Comment by marty1885** [comment] 2020-09-19 12:52
Hmm... So maybe a new behavior of GCC 10 or Ubuntu have applied patches to their GCC? Weird... (Note for myself: How did Etaler didn't ran into the same issue?)

I also tried clang 10. But it is complaining about Eigen.

```
/home/marty/Documents/not-my-projects/htm.core/build/ThirdParty/eigen/eigen-src/Eigen/src/Core/MatrixBase.h:139:14: error: definition of implicit copy constructor for 'MatrixBase<Eigen::Block<Eigen::Matrix<int, -1, -1, 0, -1, -1>, -1, 1, true> >' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
    Derived& operator=(const MatrixBase& other);
```

**Comment by dkeeney** [comment] 2020-09-19 13:26
I setup a virtual machine on Mint (latest stable build).
Here is what I did:
```
sudo apt update
sudo apt upgrade
sudo apt install build-essential
sudo apt install git
python3 -V                #To confirm that python3 is already installed
sudo apt install python3-pip
sudo apt install cmake
cd to where-clone-will-be-placed.
git clone https://github.com/htm-community/htm.core.git
cd htm.core
pip3 install -r requirements.txt
python3 setup.py install --user --force
python3 setup.py test
```

Everything worked fine.  All tests pass.

**Comment by dkeeney** [comment] 2020-09-19 15:48
My previous builds were g++9 which I think is the default.
Ok, back on Ubuntu, switched to the new g++10 compiler.  It will build with C++17
Python 3.8.2
Delete the `build` folder.
Building with `python3 setup.py install --user --force`
I got a few warnings while compiling the Third Party packages but it built ok. 
Ran the unit tests.
The ConnectionsPerformanceTest errored out ... taking too long.  Not sure what that is about.

But I did not see your error.

**Comment by Sedom9** [comment] 2020-09-21 08:18
Sorry, I got some errors.  I have Linux Mint 19.1. But I saw your previous message. And I have compiler g++ 8. It is not difficult to install Ubuntu 20.04. What do you think about this idea?

**Comment by marty1885** [comment] 2020-09-21 11:47
I tried to build cereal from scratch and figure out what happening. Then I encounter the same message when cereal 1.3.0 using Arch Linux's PKGBUILD script (which does not set `-Werror`). But the message is a warning instead of error in the PKGBUILD. It *seems* that either Ubuntu have patched GCC to disable the error or some versions of GCC have a bug leading the error not shown.

I guess I could always patch -Werror out. But is this a proper solution?

**Comment by breznak** [comment] 2020-09-21 12:54
> I could always patch -Werror out. But is this a proper solution? 

yes, this is a quick hack. We've recently revisited an issue where cmake should pass `SYSTEM` to the includes, so that our extra pedantic `-Werror` is not triggered by 3rd party includes. Probably the same logic should be applied to compiling any 3rd sources too.

**Comment by Sedom9** [comment] 2020-09-21 13:03
Is it only about Linux Arch ?

**Comment by marty1885** [comment] 2020-09-21 13:03
@breznak I think the deeper issue is why it compiles on Ubuntu but not Mint and Arch (`-Werror` is fine). Like, patching the compiler to suppress warnings is quite odd and I don't think Ubuntu does that. But there's not much other reasons for GCC not complaining on Ubuntu.

**Comment by dkeeney** [comment] 2020-09-21 13:07
I started with a fresh clone which includes that SYSTEM change.  The SYSTEM prefix is now applied to all third party includes. This basically suppresses warnings caused by the third party code being included.
I tried the latest Mint and there was no error.

**Comment by dkeeney** [comment] 2020-09-21 13:18
@Sedom9, @marty1885, can you try getting a fresh clone of htm.core and see if that solves the problem?

**Comment by marty1885** [comment] 2020-09-21 13:19
@dkeeney Which branch/commit/fork?

**Comment by Sedom9** [comment] 2020-09-21 13:34
Yes, I can. But I downloaded 10 hours ago last time. Try now?  I can install Linux Mint 20 (last version) or Ubuntu 20.04. What do you recommend?

**Comment by breznak** [comment] 2020-09-21 14:21
> The SYSTEM prefix is now applied to all third party includes. This basically suppresses warnings caused by the third party code being included. 

@dkeeney but the cereal is also built as a lib (not only includes). Does the SYSTEM cover that case already as well?

**Comment by dkeeney** [comment] 2020-09-21 14:58
Cereal is include only.  There is no lib.
This "SYSTEM" fix is already in the Master branch and has been there for over a week.

So, @Sedom9 if you are still having the problem then this is not the solution we are looking for.

There must be something else that is different between what I have and what @Sedom9 and @marty1885 are running.

**Comment by Sedom9** [comment] 2020-09-22 09:37
I downloaded htm.core . Repeat this commands: 
```
sudo apt update
sudo apt upgrade
sudo apt install build-essential
sudo apt install git
python3 -V                #To confirm that python3 is already installed
sudo apt install python3-pip
sudo apt install cmake
cd to where-clone-will-be-placed.
git clone https://github.com/htm-community/htm.core.git
cd htm.core
pip3 install -r requirements.txt
python3 setup.py install --user --force
```

I got the same errors. I used Linux 19.1. Now I will try to use Ubuntu 20.04

**Comment by dkeeney** [comment] 2020-09-22 13:20
I also have a VM containing  Ubuntu 19.10, GCC 9.2.1, Python 3.7.5 
This built without errors or warnings.
So those things do not seem to be the cause of the problem.

I am getting an error when running the unit test, unrelated to problem at hand.
I saw this on Ubuntu 20.04 as well.
```
Expected: (tim) <= (8.5f * Timer::getSpeed()), actual: 9.04811 vs 8.66786
[  FAILED  ] ConnectionsPerformanceTest.testSP (9074 ms)
```
@breznak you might want to check this out.

**Comment by Sedom9** [comment] 2020-09-23 13:12
Yesterday, I installed Ubuntu 20.04. And repeat all commands. Everything ok!  I think it's about a new kernel and new compiler g++ 9 (or above). Thanx for your help. @dkeeney @marty1885  @breznak

**Comment by fcr** [comment] 2020-09-29 13:03
I am now having trouble building on my Mac, Catalina 10.15.7, clang-1200.0.32.2, Xcode 12.0.1. I have tried with Python 3.7.7 and Python 3.8.3.
This is the error I get: 
[  0%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/algorithms/Anomaly.cpp.o
[  0%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/algorithms/SDRClassifier.cpp.o
[  2%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/algorithms/Connections.cpp.o
[  2%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/algorithms/AnomalyLikelihood.cpp.o
/Users/fred/Development/htm.core/src/htm/algorithms/Connections.cpp:763:19: error: loop variable 'cellData' of type 'const htm::CellData' creates a copy from type 'const htm::CellData'
      [-Werror,-Wrange-loop-analysis]
  for( const auto cellData : self.cells_ )
                  ^
/Users/fred/Development/htm.core/src/htm/algorithms/Connections.cpp:763:8: note: use reference type 'const htm::CellData &' to prevent copying
  for( const auto cellData : self.cells_ )
       ^~~~~~~~~~~~~~~~~~~~~
                  &
/Users/fred/Development/htm.core/src/htm/algorithms/Connections.cpp:829:18: error: loop variable 'cellD' of type 'const htm::CellData' creates a copy from type 'const htm::CellData'
      [-Werror,-Wrange-loop-analysis]
  for(const auto cellD : cells_) {
                 ^
/Users/fred/Development/htm.core/src/htm/algorithms/Connections.cpp:829:7: note: use reference type 'const htm::CellData &' to prevent copying
  for(const auto cellD : cells_) {
      ^~~~~~~~~~~~~~~~~~
                 &
[  3%] Building CXX object src/CMakeFiles/LibrarySource.dir/htm/algorithms/SpatialPooler.cpp.o
2 errors generated.
gmake[2]: *** [src/CMakeFiles/LibrarySource.dir/build.make:108: src/CMakeFiles/LibrarySource.dir/htm/algorithms/Connections.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:473: src/CMakeFiles/LibrarySource.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 374, in <module>
    getExtensionFiles(platform, build_type)
  File "setup.py", line 239, in getExtensionFiles
    generateExtensions(platform, build_type)
  File "setup.py", line 286, in generateExtensions
    subprocess.check_call(["cmake", "--build", ".", "--target", "install", "--config", build_type, "--", "-j", "4"])
  File "/Users/fred/opt/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.

**Comment by breznak** [comment] 2020-09-29 18:04
> for(const auto cellD : cells_) { 

this maybe should be `for(const auto& cellD: cells_)` 
and the new XCode12 reports that.

**Comment by fcr** [comment] 2020-09-29 18:55
> > for(const auto cellD : cells_) {
> 
> this maybe should be `for(const auto& cellD: cells_)`
> and the new XCode12 reports that.

From my tries to bypass this problem I think that there quite a few places that will need this correction. (Don't look at me, as you know, I am not a C++ person :-\ )

**Comment by breznak** [comment] 2021-02-20 13:05
Closing as rather outdated, we have bumped a lot of dependencies recently and switched to py3.8, so chances are "things start working :) "

**Closed by breznak** 2021-02-20 13:05 UTC
